name = "siren-web"
main = "build/worker/shim.mjs"
compatibility_date = "2024-05-23"
minify = true
workers_dev = true

[[kv_namespaces]]
binding = "SIREN"
id = "0e4382b1023e49af9b3abf00e2855bbc" 

[build]
command = "cargo install -q worker-build && worker-build --release"

[env.dev]
build = { command = "cargo install -q worker-build && worker-build --dev" }

[vars]
UUID = "aacac2d2-cac8-442a-9f2c-4e4f807065f5"
MAIN_PAGE_URL = "https://raw.githubusercontent.com/zerokit-769/cf/refs/heads/main/web/index.html"
SUB_PAGE_URL = "https://raw.githubusercontent.com/zerokit-769/cf/refs/heads/main/web/sub.html"
LINK_PAGE_URL = "https://raw.githubusercontent.com/zerokit-769/SirenWeb/refs/heads/master/web/link.html"
